name: Weekly
on:
  # Every Wednesday at 08:00 UTC
  schedule: [{cron: '0 8 * * 3'}]
  # Enable manual trigger
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Plot
      run: |
        set -Eeuxo pipefail

        ./plot.py plot.png | tee toot.txt

    - name: Toot
      run: |
        set -Eeuxo pipefail

        echo '{{secrets.MASTO_ACCESS_KEY}}' >token.secret
        ./toot.py toot.txt plot.png
